apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: front-end
  name: front-end-lb
  namespace: sock-shop
spec:
  ports:
  - port: 88
    protocol: TCP
    targetPort: 8079
  selector:
    name: front-end
  type: LoadBalancer
