apiVersion: v1
kind: Service
metadata:
  labels:
    operated-prometheus: "true"
  name: prometheus-operated-lb
  namespace: default
spec:
  ports:
  - name: web
    port: 9099
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  type: LoadBalancer
